name: 'Main'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: run deployment via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: bash $HOME/onmy-website-deployments/template-with-fastify.sh